### ISSUE TITLE
[FEAT]: SIGN UP AND LOG IN FORM IS MISSING

### ISSUE THREAD

**Issue by AnitSarkar123** [Pritanshu69/Amazon_homepage-#1]
The sign up and login form is a important feature of a website.but this is missing in this website

**Comment by rko0211** [comment]
Hello please assign me this task under apertre24 i want to contribute in this issue. Thank you

**Comment by AnitSarkar123** [comment]
Also Please, assign me this task under apertre24 i want to contribute in this issue. Thank you

**Comment by Debaditya-Som** [comment]
> Hello please assign me this task under apertre24 i want to contribute in this issue. Thank you

We appreciate your will to contribute to this issue, but it has been created by @AnitSarkar123  and he is willing to contribute to it. So, we would suggest you to look for another issue or create an issue of your own. Incase @AnitSarkar123  is not willing or is unable to work on this issue we'll assign you :)

**Comment by AnitSarkar123** [comment]
can i use bootstrap ?

**Comment by Debaditya-Som** [comment]
@AnitSarkar123 

please elaborate your approach, if you will add JWT authentication or not.

**Comment by AnitSarkar123** [comment]
No I don't want to add JWT authentication.

**Comment by Debaditya-Som** [comment]
> No I don't want to add JWT authentication.and also all given data stored in database..and I am only interested in frontend part

Mostly when you say you want to work on any sign up page you need to check for the authentication part too

**Comment by Debaditya-Som** [comment]
![image](https://github.com/Pritanshu69/Amazon_homepage-/assets/121785700/df542f6a-02b3-405a-8d22-d5e08e7d74cc)

**Comment by Pritanshu69** [comment]
![image](https://github.com/Pritanshu69/Amazon_homepage-/assets/116452282/9e0e0a99-cce5-4791-ac53-f6c0195d6e0c)

**Comment by AnitSarkar123** [comment]
😅😅ok then assign this to other's but at this time I don't want to work on backend mostly in HTML,CSS,JS project...... because of handelbers and pug conversion is very time taking for me

**Comment by Debaditya-Som** [comment]
> 😅😅ok then I can do it by firebase but I can't give my apikey,authdomain, projecid.....etc in PR.....😅😅😅

Thats alright just tell us whether it can be deployed?

**Comment by AnitSarkar123** [comment]
> > 😅😅ok then I can do it by firebase but I can't give my apikey,authdomain, projecid.....etc in PR.....😅😅😅
> 
> Thats alright just tell us whether it can be deployed?

Sorry I take the api key etc.. from an .env file and I make an env.sample (i give it)file you make an project on firebase and take what keys required to there and put all of this that places..and then you can test the app.

And it deployed on vercel

**Comment by Debaditya-Som** [comment]
> > > 😅😅ok then I can do it by firebase but I can't give my apikey,authdomain, projecid.....etc in PR.....😅😅😅
> > 
> > 
> > Thats alright just tell us whether it can be deployed?
> 
> Sorry I take the api key etc.. from an .env file and I make an env.sample (i give it)file you make an project on firebase and take what keys required to there and put all of this that places..and then you can test the app.
> 
> And it deployed on vercel

It's alright Anit, but see this is just a basic Amon homepage clone made out of HTML and CSS, and we have kept it simple so that beginners can contribute easily. So, in my opinion this is actually a good issue, but first this is just a homepage clone and secondly, it's made with HTML and CSS so in order to maintain the simplicity we are closing this issue
