### ISSUE TITLE
Change the CSS of the footer section

### ISSUE THREAD

**Issue by Sapta-Dev27** [Pritanshu69/Amazon_homepage-#10]
I would like to change the CSS of the footer section , add links to the texts just like the Original Amazon website , make it more realistics , such that when you would hover on the texts , it would act like a link that would direct you to the particular sites .

**Comment by Debaditya-Som** [comment]
Hi @Sapta-Dev27 , thanks for showing your interest in working on this issue, but this issue has already been referred in #4
