### ISSUE TITLE
Change the CSS of the links in the shoping section

### ISSUE THREAD

**Issue by Sapta-Dev27** [Pritanshu69/Amazon_homepage-#11]
I would like to change the CSS of the links in the shopping section , apply the CSS and add hover effect  ,add list style effects

**Comment by AnuragMalasi** [comment]
> I would like to change the CSS of the links in the shopping section , apply the CSS and add hover effect ,add list style effects

i can do this task. please assign it to me.
thanks :)

**Comment by Debaditya-Som** [comment]
> i can do this task. please assign it to me. thanks :)

ig @Sapta-Dev27 is already assigned with another issue , so @AnuragMalasi you can work on this
