### ISSUE TITLE
Want to create a beautiful signIn and signUp page for this website

### ISSUE THREAD

**Issue by rko0211** [Pritanshu69/Amazon_homepage-#113]
Kindly assign me this task

**Comment by Debaditya-Som** [comment]
here you go @rko0211 , but make sure it connects to the main site (the main website)

**Comment by Debaditya-Som** [comment]
and also could you just mention what are you going to do...we'll adjust the level of label according to that

**Comment by Debaditya-Som** [comment]
> I would create the responsive front end of both sign in and sign up page and use JS validation..

okay now ths kinda a hard level task

**Comment by Debaditya-Som** [comment]
All the best bro :)
