### ISSUE TITLE
header is not arranged properly and add links in the footer

### ISSUE THREAD

**Issue by AnuragMalasi** [Pritanshu69/Amazon_homepage-#116]
-->i will be arranging header of this website
![Screenshot 2024-01-10 155244](https://github.com/Pritanshu69/Amazon_homepage-/assets/125523667/5efb64ee-0e94-41ed-b8b2-707a4fd3a7ab)
-->links to different country's amazon website is not added in the footer so i will be adding those

**Comment by AnuragMalasi** [comment]
@Debaditya-Som please assign this issue to me
thanks :)

**Comment by Debaditya-Som** [comment]
Here you go @AnuragMalasi
