### ISSUE TITLE
[FEATURE] [UI/UX] Logo of the website is required

### ISSUE THREAD

**Issue by Debaditya-Som** [Pritanshu69/Amazon_homepage-#12]
The current state of the website is missing the amazon logo. So, the logo needs to be added to the website,

**Comment by AnitSarkar123** [comment]
Assign me under Apertre'24

**Comment by Debaditya-Som** [comment]
> Assign me under Apertre'24

Thanks for showing your interest in our project, we'll start assigning the issues from 3rd Jan
