### ISSUE TITLE
Adding an animation on scroll 

### ISSUE THREAD

**Issue by 123shreyanvi** [Pritanshu69/Amazon_homepage-#131]
Adding a sign-in page and connecting it to the Hello, Sign in Accounts & Lists button on the main page
Adding some animation as the page slides up

**Comment by 123shreyanvi** [comment]
Plz do assign me this

**Comment by Debaditya-Som** [comment]
The issue regarding sign-in page has already been referred to in another issue

**Comment by 123shreyanvi** [comment]
> The issue regarding sign-in page has already been referred to in another issue

Ok
