### ISSUE TITLE
Arranging and adding more sections

### ISSUE THREAD

**Issue by Debaditya-Som** [Pritanshu69/Amazon_homepage-#133]
![image](https://github.com/Pritanshu69/Amazon_homepage-/assets/121785700/ae0cf065-f0d5-4bd2-9b55-3cd0dc9976b3)

**Comment by YooAshu** [comment]
i can add groups like this 
![Screenshot (89)](https://github.com/Pritanshu69/Amazon_homepage-/assets/95643200/2bad1ab8-3f8c-46c8-b9c7-c5fd0a554d27)
and a scroll bar like this today deals 
![Screenshot (90)](https://github.com/Pritanshu69/Amazon_homepage-/assets/95643200/27c9effb-0039-4d3d-954c-14f5106e813e)
