### ISSUE TITLE
Add new Feature : API boxes

### ISSUE THREAD

**Issue by apu52** [Pritanshu69/Amazon_homepage-#139]
**Describe the feature you are requesting**

Hello Sir,
I want to add some cool badges in this repo like
- open issues
- contributor
- open PR
- last commites
this type of cool API badges
It will be very helpful to showcase the stats of your Repo as well as will attract more contributors.
**Additional context(if any)**

![image](https://github.com/Pritanshu69/Amazon_homepage-/assets/114172928/8d83ca66-5936-4bf5-8876-6002ccd9313a)

***Are you contributing under any open-source program ?***

APERTRE'24

**Comment by apu52** [comment]
@Pritanshu69 Please assign me this issue under APERTRE'24

**Comment by Debaditya-Som** [comment]
here you go @apu52

**Comment by apu52** [comment]
> here you go @apu52

@Debaditya-Som THE ISSUE IS NOT ASSIGNED. ONLY THE LABLES ARE ATTACHED
