### ISSUE TITLE
I want to change the title which is not looking same as amazon original website.

### ISSUE THREAD

**Issue by SAYAN-DAN** [Pritanshu69/Amazon_homepage-#14]

**Comment by Debaditya-Som** [comment]
![image](https://github.com/Pritanshu69/Amazon_homepage-/assets/121785700/284136bc-e430-44c3-8f0c-cdc26f37c241)

**Comment by Pritanshu69** [comment]
![image](https://github.com/Pritanshu69/Amazon_homepage-/assets/116452282/8d837933-9a63-4c17-b037-325a6e3b302c)

**Comment by Pritanshu69** [comment]
Your issue is not a issue or a relevant feature so we are closing it. Thank you @SAYAN-DAN keep coding...
