### ISSUE TITLE
On scroll animations

### ISSUE THREAD

**Issue by lord-cyclone100** [Pritanshu69/Amazon_homepage-#144]
I want to add on scroll animations to the webpage
Pls assign me this task if you like my idea @Debaditya-Som @Pritanshu69

**Comment by Debaditya-Som** [comment]
HI @lord-cyclone100 this issue has already been referred in another issue, if you want and the person who opened the issue permits we can assign you in that one

**Comment by lord-cyclone100** [comment]
ok
