### ISSUE TITLE
Designer Scrollbars

### ISSUE THREAD

**Issue by lord-cyclone100** [Pritanshu69/Amazon_homepage-#145]
I want to add css to the scroll bars in the webpage
pls assign me this task @Pritanshu69 @Debaditya-Som

**Comment by Debaditya-Som** [comment]
This has already been referred in #134

**Comment by lord-cyclone100** [comment]
@Debaditya-Som by designer scrollbar i meant this one
![WhatsApp Image 2024-01-15 at 15 02 12_41211ae1](https://github.com/Pritanshu69/Amazon_homepage-/assets/121711381/7be66e7e-ec15-483e-bc56-c21391d36a7b)
This is not present in the website
