### ISSUE TITLE
UI enhancement 

### ISSUE THREAD

**Issue by rko0211** [Pritanshu69/Amazon_homepage-#147]
The current website is not good looking, i can fix it , please assign me this one

![ui](https://github.com/Pritanshu69/Amazon_homepage-/assets/97402824/a5272814-51e4-441f-8bc6-c710835d8284)

**Comment by Debaditya-Som** [comment]
@rko0211 this issue seems to be fixed as the website is completely looking fine

**Comment by rko0211** [comment]
![Screenshot from 2024-01-16 14-49-19](https://github.com/Pritanshu69/Amazon_homepage-/assets/97402824/5550becd-d3cb-486a-84f2-7a7ac17f115a)

Actually when we click the link of this website then above view is appeared in front of us , see it
