### ISSUE TITLE
adding links in the body section of the website

### ISSUE THREAD

**Issue by AnuragMalasi** [Pritanshu69/Amazon_homepage-#148]
![Screenshot 2024-01-15 092054](https://github.com/Pritanshu69/Amazon_homepage-/assets/125523667/e4a84f49-53c1-4312-ab93-40e34fc3fa74)

**Comment by AnuragMalasi** [comment]
@Debaditya-Som please assign this issue to me
thanks :)

**Comment by AnuragMalasi** [comment]
@Debaditya-Som please assign this issue to me
thanks :)

**Comment by Debaditya-Som** [comment]
> @Debaditya-Som please assign this issue to me thanks :)

yep surely

**Comment by Debaditya-Som** [comment]
Here you go @AnuragMalasi .. see #155
