### ISSUE TITLE
adding link in the hello sign in button and adding links in the body section of the website

### ISSUE THREAD

**Issue by AnuragMalasi** [Pritanshu69/Amazon_homepage-#155]
![sc'](https://github.com/Pritanshu69/Amazon_homepage-/assets/125523667/a9cb4b66-cd0b-4294-82e0-6bcf446edfd9)
this is not linked with sign in page

**Comment by AnuragMalasi** [comment]
@Debaditya-Som please assign this issue to me 
thanks :)

**Comment by Debaditya-Som** [comment]
Here you go @AnuragMalasi
