### ISSUE TITLE
Update Readme 

### ISSUE THREAD

**Issue by arghadipmanna101** [Pritanshu69/Amazon_homepage-#158]
- will add photos
- will add gif
- will stylize the readme
- will add how to contribute
- Will add contributors name in Readme file.

**Comment by arghadipmanna101** [comment]
please assign me under Apertre

**Comment by Debaditya-Som** [comment]
here you go @arghadipmanna101

**Comment by arghadipmanna101** [comment]
thank you

**Comment by abhraneel2004** [comment]
I want to work on the Readme too. Is there any way @Debaditya-Som @Pritanshu69 ??

**Comment by Pritanshu69** [comment]
@abhraneel2004 here you go

**Comment by Pritanshu69** [comment]
![image](https://github.com/Pritanshu69/Amazon_homepage-/assets/116452282/a74f9e5b-c873-4650-84b9-ea9957539203)
@abhraneel2004
