### ISSUE TITLE
Give Crousel effect in the home page 

### ISSUE THREAD

**Issue by Sapta-Dev27** [Pritanshu69/Amazon_homepage-#17]
I would like to give Carousel effect by making use of Carousel in the home page , just like how it is shown the amazon website .
Carousel effect will be given by the use of Bootstarp 
![Uploading Screenshot 2024-01-02 17.11.03.png…]()

**Comment by Debaditya-Som** [comment]
Here you go @Sapta-Dev27

**Comment by Pritanshu69** [comment]
@Sapta-Dev27 it's been 4 days we have assigned you this. Any update?

**Comment by Sapta-Dev27** [comment]
Yeah , actually I tried to work on that issue previously but unfortunately
I am not able to add that feature in the home page..u can close the issue
or can assign it someone else

**Comment by Pritanshu69** [comment]
No problem brother @Sapta-Dev27 . It's good to see your quick response.
