### ISSUE TITLE
adding links in the individual images in the shopping section

### ISSUE THREAD

**Issue by AnuragMalasi** [Pritanshu69/Amazon_homepage-#179]
![Screenshot 2024-01-20 001407](https://github.com/Pritanshu69/Amazon_homepage-/assets/125523667/63ed21fb-1f99-4c06-bf56-0496d28c0000)
these images doesn't have individual links to the shown products like in the original website. So i will be adding those.
and also i will be changing some css properties of this section.

**Comment by AnuragMalasi** [comment]
@Debaditya-Som kindly assign this to me

**Comment by Pritanshu69** [comment]
It's already have been done bro.
