### ISSUE TITLE
want to modify the navbar section

### ISSUE THREAD

**Issue by SAYAN-DAN** [Pritanshu69/Amazon_homepage-#18]
I see that the navbar is not looking good and the same as the original Amazon website so I want to modify it.

**Comment by Debaditya-Som** [comment]
Yes surely you can but you need to give the PR in the test branch

**Comment by Pritanshu69** [comment]
@SAYAN-DAN you haven't messaged us or did any commit since more than 2 days so we are removing you from this easy segment issue.

**Comment by Debaditya-Som** [comment]
This is an open issue anyone wants to work on it?

**Comment by YooAshu** [comment]
@Debaditya-Som i want to work on this

**Comment by Debaditya-Som** [comment]
> @Debaditya-Som i want to work on this

Here you go :)
