### ISSUE TITLE
[Bug]fix the footer section in html 

### ISSUE THREAD

**Issue by aniketde1112** [Pritanshu69/Amazon_homepage-#19]
Problem :- the context to b changed
Solution:- the option should b able to go to the desired  link

**Comment by AnuragMalasi** [comment]
i can do this task...please assign this issue to me.
thanks

**Comment by AnuragMalasi** [comment]
> Problem :- the context to b changed Solution:- the option should b able to go to the desired link

i can do this task....please assign this issue to me.
thanks

**Comment by Sapta-Dev27** [comment]
I would also like to contribute in the same issue , please assign the task to me

**Comment by Sneha123-zudo** [comment]
I'm intrested in fixing this issue please assign me this issue
