### ISSUE TITLE
[BUG]: TAB AND MOBILE VIEW IS DISTRUBED

### ISSUE THREAD

**Issue by AnitSarkar123** [Pritanshu69/Amazon_homepage-#2]

**Comment by rko0211** [comment]
Hello I want to contribute in this issue kindly assign me this task. Thank you

**Comment by AnitSarkar123** [comment]
Also, please assign me this task under apertre24 i want to contribute in this issue. Thank you

**Comment by Debaditya-Som** [comment]
> Hello I want to contribute in this issue kindly assign me this task. Thank you

We appreciate your will to contribute to this issue, but it has been created by @AnitSarkar123  and he is willing to contribute to it. So, we would suggest you to look for another issue or create an issue of your own. Incase @AnitSarkar123  is not willing or is unable to work on this issue we'll assign you :)

**Comment by Soumyajit-Koley** [comment]
Hey I'm interested can you please assign me this

**Comment by Debaditya-Som** [comment]
@AnitSarkar123 here you go, but make sure to sync the branch before submitting the PR into the test branch and not the main branch

**Comment by AnitSarkar123** [comment]
Assign it to another contributor..... because of some reason I don't able to contribute in Apertre'24 at this time.Sorry

**Comment by Debaditya-Som** [comment]
> Assign it to another contributor..... because of some reason I don't able to contribute in Apertre'24 at this time.Sorry

Okay, @Soumyajit-Koley do you want to work on this issue?
