### ISSUE TITLE
Create an option to show the prices in INR 

### ISSUE THREAD

**Issue by Snehan-Maity** [Pritanshu69/Amazon_homepage-#20]
The site should have an option to change the currency according to users' location.

**Comment by Debaditya-Som** [comment]
Here you go @Snehan-Maity, give the pr to the test branch

**Comment by Pritanshu69** [comment]
@Snehan-Maity what's the update bro?

**Comment by Pritanshu69** [comment]
@Snehan-Maity we are closing your issue because you are taking too much time and not only that, You are not even giving any texts neither here or in the discord. So we are closing it.
![image](https://github.com/Pritanshu69/Amazon_homepage-/assets/116452282/92fb9571-1ec2-4a4c-b5d6-b0829db8662c)
