### ISSUE TITLE
Back to top link is not working 

### ISSUE THREAD

**Issue by rko0211** [Pritanshu69/Amazon_homepage-#23]
![Screenshot from 2024-01-02 23-02-12](https://github.com/Pritanshu69/Amazon_homepage-/assets/97402824/7dec44c6-99ee-407c-9685-2bf962096462)

Back to top link is not working . I can fix it can you assign me this task under apertre24. Thank you

**Comment by Debaditya-Som** [comment]
It seems that this issue has already been covered by another issue #6 , so I'm closing it
