### ISSUE TITLE
Make shop section responsive as well as look more cool like Amazon

### ISSUE THREAD

**Issue by utsav306** [Pritanshu69/Amazon_homepage-#29]
Shop section view is not responsive as well as not up to mark.

**Comment by cjstyles6** [comment]
@Pritanshu69 can i work on this issue

**Comment by Pritanshu69** [comment]
@utsav306 can you plz elaborate me which particular section are you taking about? like you can also attach a ss marking it too.

**Comment by utsav306** [comment]
> @utsav306 can you plz elaborate me which particular section are you taking about? like you can also attach a ss marking it too.

want to make the shop section responsive . In mobile view it doesnt looks good.
![Screenshot (202)](https://github.com/Pritanshu69/Amazon_homepage-/assets/116065052/68ae3320-0b19-444e-8056-d837e2b69ec0)

**Comment by Pritanshu69** [comment]
Here you go @utsav306 we have assigned this issue to you. Make sure you complete this within 3 days and pr into the test branch not into the main branch.

**Comment by Pritanshu69** [comment]
ok done we have merged your PR.
