### ISSUE TITLE
[FEATURE]: Design Footer Section

### ISSUE THREAD

**Issue by Geeks-Arpan** [Pritanshu69/Amazon_homepage-#4]

**Comment by rko0211** [comment]
Hello i want to work in this issue kindly assign me this one under Apertre24 thank you

**Comment by Tuhin114** [comment]
I want to work in this section please assign me....

**Comment by Sneha123-zudo** [comment]
I'm intrested in fixing this issue please assign me this issue

**Comment by Debaditya-Som** [comment]
@Geeks-Arpan here you go, try to finish the issue within 3 days and always sync our branch before submitting the PR into the test branch

**Comment by Debaditya-Som** [comment]
@Geeks-Arpan how are you progressing with the issue?
