### ISSUE TITLE
adding new section

### ISSUE THREAD

**Issue by Rai-Adhikary004** [Pritanshu69/Amazon_homepage-#40]
Adding a new arrival section, so that people can see new things quickly.

**Comment by Debaditya-Som** [comment]
That's a nice one

**Comment by Debaditya-Som** [comment]
Here you go @Rai-Adhikary004 , but make sure to give the PR in the test branch and sync your repo to keep it updated and avoid merge conflict

**Comment by Pritanshu69** [comment]
@Rai-Adhikary004 you have time upto tomorrow morning ok? otherwise this issue will be aasigned to someone else!

**Comment by Pritanshu69** [comment]
Times up @Rai-Adhikary004 I am closing your issue!
![image](https://github.com/Pritanshu69/Amazon_homepage-/assets/116452282/e07c1377-8de3-46ec-b353-3012bbb6fcf5)
