### ISSUE TITLE
[BUG] Fix image in Responsive Web Design

### ISSUE THREAD

**Issue by Geeks-Arpan** [Pritanshu69/Amazon_homepage-#5]
![Amazon](https://github.com/Pritanshu69/Amazon_homepage-/assets/99377659/174f082f-9f72-4ba7-8c29-fb0cf2bbcc87)

**Comment by Debaditya-Som** [comment]
@Geeks-Arpan could you please elaborate on what is this issue really about? It seems to be little vague

**Comment by rko0211** [comment]
Hello I want to contribute in this issue as cards are not responsive in mobile device. Kindly assign me this task under apettre24.

**Comment by Debaditya-Som** [comment]
The images are responsive now and it's working fine. Thank you for opening the issue, but now we re closing it as it has now been resolved
