### ISSUE TITLE
[Bug] Back to top attribute is not working and even meta description not given

### ISSUE THREAD

**Issue by aniketde1112** [Pritanshu69/Amazon_homepage-#6]
Current problem - On clicking the back to top button it is not working at all and meta description not given
Suggested solution: On clicking the back to top button it should be able to go to the top of the website and description should be written

**Comment by AnitSarkar123** [comment]
Project Admin please assign me this task under apertre24 i want to contribute in this issue. Thank you

**Comment by aniketde1112** [comment]
i can contribute to  it.

**Comment by Debaditya-Som** [comment]
> Project Admin please assign me this task under apertre24 i want to contribute in this issue. Thank you

We appreciate your will to contribute to this issue, but it has been created by @aniketde1112 and he is willing to contribute to it. So, we would suggest you to look for another issue or create an issue of your own. Incase @aniketde1112 is not willing or is unable to work on this issue we'll assign you :)

**Comment by AnitSarkar123** [comment]
> > Project Admin please assign me this task under apertre24 i want to contribute in this issue. Thank you
> 
> We appreciate your will to contribute to this issue, but it has been created by @aniketde1112 and he is willing to contribute to it. So, we would suggest you to look for another issue or create an issue of your own. Incase @aniketde1112 is not willing or is unable to work on this issue we'll assign you :)

Please assign both of us and merge the pull request first come first serve basics

**Comment by Debaditya-Som** [comment]
Here you go @aniketde1112

**Comment by guddubasu** [comment]
I do want to work on this issue

**Comment by Debaditya-Som** [comment]
> I do want to work on this issue

Thanks for showing your interest in working on this issue but it has already been assigned to @aniketde1112 , so either create an issue of your own or check some other issue

**Comment by Pritanshu69** [comment]
![image](https://github.com/Pritanshu69/Amazon_homepage-/assets/116452282/5e97e2f1-76a1-4929-9b20-55c627d5a582)
