### ISSUE TITLE
The Go to Amazon.in message is not responsive in mobile device

### ISSUE THREAD

**Issue by rko0211** [Pritanshu69/Amazon_homepage-#60]
![Screenshot from 2024-01-04 11-38-02](https://github.com/Pritanshu69/Amazon_homepage-/assets/97402824/93828a16-fe0d-40ea-bd46-e17e9c611191)

Kindly review my issue and assign me under apertre24, i want to work in this issue. Thank you.

**Comment by Debaditya-Som** [comment]
Here you go @rko0211 , submit the PR within 24hrs and into the test branch
