### ISSUE TITLE
box pics are not coming

### ISSUE THREAD

**Issue by Pritanshu69** [Pritanshu69/Amazon_homepage-#63]
![Screenshot 2024-01-04 181604](https://github.com/Pritanshu69/Amazon_homepage-/assets/116452282/54170de5-33f3-4a34-9fe0-cae51d8091ad)

**Comment by deepbeatz** [comment]
@Debaditya-Som as you closed issue #71 assign me this issue here... with apertre tag

**Comment by Debaditya-Som** [comment]
> @Debaditya-Som as you closed issue #71 assign me this issue here... with apertre tag

yep surely

juts make sure you sync your fork before submitting the PR into the test branch

**Comment by deepbeatz** [comment]
sure

**Comment by utsav306** [comment]
I can solve this problem !!  Assign it to me  !

**Comment by deepbeatz** [comment]
pr sent #83

**Comment by Debaditya-Som** [comment]
> I can solve this problem !! Assign it to me !

@utsav306 here you go

**Comment by utsav306** [comment]
@Debaditya-Som  PR sent ! check if there are any issues !

**Comment by Debaditya-Som** [comment]
> @Debaditya-Som  PR sent ! check if there are any issues !

Yup were checking it
