### ISSUE TITLE
Cards are not beautiful 

### ISSUE THREAD

**Issue by rko0211** [Pritanshu69/Amazon_homepage-#64]
![cards](https://github.com/Pritanshu69/Amazon_homepage-/assets/97402824/3b0b6803-f757-4e0e-8aec-3f3202c21772)
Kindly review my issue and assign me this task . I want to solve it. Thank you...

**Comment by Debaditya-Som** [comment]
This issue has already been referred in #63 so you may ping there in order to work on that issue
