### ISSUE TITLE
Adding more boxes in shoping section and also adding links in the footer sections.

### ISSUE THREAD

**Issue by AnuragMalasi** [Pritanshu69/Amazon_homepage-#65]
what has to be done:-
1) going to add more boxes in the shopping section like bestseller,  birthday store , etc.
2) adding appropriate links in the footer section as the links are not clickable.
]
![Screenshot 2024-01-04 181843](https://github.com/Pritanshu69/Amazon_homepage-/assets/125523667/7a8581cc-630b-4840-9c12-b9707eb19688)
3) add working to (back to top) button & (click here to go to amazon.in)

**Comment by Debaditya-Som** [comment]
okay sure ahead with this issue!

**Comment by AnuragMalasi** [comment]
> okay sure ahead with this issue!

please assign this issue to me
