### ISSUE TITLE
Cursor should be pointer and the images should be responsive

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [Pritanshu69/Amazon_homepage-#7]
On sign in option, return option and on add to cart option cursor should be pointer. And the images are not responsive.

**Comment by Debaditya-Som** [comment]
That's a good issue, would you like to work on this issue?

**Comment by Ishitamukherjee2004** [comment]
> That's a good issue, would you like to work on this issue?

Definitely i want to work

**Comment by Debaditya-Som** [comment]
> > That's a good issue, would you like to work on this issue?
> 
> Definitely i want to work

Here you go @Ishitamukherjee2004

**Comment by Pritanshu69** [comment]
@Ishitamukherjee2004 you have time upro today 11:59 okay? if you don't give us any reply or don't send pr then we'll delete this issue .

**Comment by Ishitamukherjee2004** [comment]
> @Ishitamukherjee2004 you have time upro today 11:59 okay? if you don't give us any reply or don't send pr then we'll delete this issue .

70% of the work is already done......I'll submit before 11:59 for sure.

**Comment by Debaditya-Som** [comment]
> > @Ishitamukherjee2004 you have time upro today 11:59 okay? if you don't give us any reply or don't send pr then we'll delete this issue .
> 
> 70% of the work is already done......I'll submit before 11:59 for sure.

sure sure carry on

**Comment by Pritanshu69** [comment]
@Ishitamukherjee2004 what's the update ?

**Comment by utsav306** [comment]
@Pritanshu69  this issue has already be fixed by me (i.e.  my first pr of making boxes ) and cursor pointer tooo !!!

**Comment by Pritanshu69** [comment]
@Ishitamukherjee2004 sorry! But we are closing your issue as you haven't submitted anything and you are taking time for a week for a medium segment problem so we are closing your pr! HAPPY CODING!
