### ISSUE TITLE
adding pics to cards and fixing back to top button

### ISSUE THREAD

**Issue by deepbeatz** [Pritanshu69/Amazon_homepage-#71]
1. Adding pics to the cards/boxes
2. back to top button not working, so i'm going to fix that

**Comment by deepbeatz** [comment]
@Debaditya-Som plz add the required labels and assign me this issue

**Comment by Debaditya-Som** [comment]
Thanks for finding out this issue, but it has already been refereed in #63 
if you are interested we can assign you that issue
