### ISSUE TITLE
Updating the redirect link to original amazon.com on home page

### ISSUE THREAD

**Issue by Umar-fr** [Pritanshu69/Amazon_homepage-#73]
![image](https://github.com/Pritanshu69/Amazon_homepage-/assets/131779792/82204e29-9ece-4f62-b391-ba58b254dfb6)

![image](https://github.com/Pritanshu69/Amazon_homepage-/assets/131779792/e1a971a2-d3d5-4500-a2c0-9ab361873700)

**Comment by Umar-fr** [comment]
@Pritanshu69 Please assign me this issue.

**Comment by Pritanshu69** [comment]
@Umar-fr the problem you have said is invalid cause the link is working fine. Maybe you have some network issues. Thank you for your courage I am closing the issue.
