### ISSUE TITLE
Making the Nav bar responsive and aligning them properly

### ISSUE THREAD

**Issue by Umar-fr** [Pritanshu69/Amazon_homepage-#74]
Making all this responsive  Today's Deals, Customer services, Registry, Gift cards, and Sell.
 Improving Alignment

**Comment by Debaditya-Som** [comment]
@Umar-fr how are you progressing with this issue?

**Comment by Umar-fr** [comment]
Hey @Debaditya-Som you can assign someone else this issue because I cannot find the time to fix it

**Comment by Debaditya-Som** [comment]
> Hey @Debaditya-Som you can assign someone else this issue because I cannot find the time to fix it

okay surely

**Comment by Sneha123-zudo** [comment]
Please assign me this issue.

**Comment by Debaditya-Som** [comment]
> Please assign me this issue.

here you go @Sneha123-zudo

**Comment by Debaditya-Som** [comment]
hi @Sneha123-zudo how are you progressing with this issue?

**Comment by Sneha123-zudo** [comment]
I will make the PR today

**Comment by Debaditya-Som** [comment]
> I will make the PR today

alright
