### ISSUE TITLE
Add some more new boxes in the shopping sectionn

### ISSUE THREAD

**Issue by Sapta-Dev27** [Pritanshu69/Amazon_homepage-#77]
Add some new boxes in the shopping section :
a) Upto 60% off sale 
b) Products starting from 99 rupees
c)Top Deals of the Day
d)End of season sale 
In all these boxes i will add the heading , link to access them , and images in the box
I would grateful to you if u allow me contribute here and assign me the issue

**Comment by Pritanshu69** [comment]
Here you go @Sapta-Dev27 make sure you complete this within 2 days and don't push into the main branch! And if you face any problem feel free to text us.
