### ISSUE TITLE
Update  Readme.md file !!

### ISSUE THREAD

**Issue by ShivanshKumar4265** [Pritanshu69/Amazon_homepage-#8]

**Comment by ShivanshKumar4265** [comment]
@Pritanshu69  assign this to me !!

**Comment by Debaditya-Som** [comment]
> @Pritanshu69 assign this to me !!

We'll start assigning when the event officially starts

**Comment by Pritanshu69** [comment]
Contribution.md file can only be edited or managed by project admins or projects mentors. mentees can edit readme.md not contribution.md . So I am closing this issue.
