### ISSUE TITLE
making links work in header section and adding more boxes in the shopping section of the website

### ISSUE THREAD

**Issue by AnuragMalasi** [Pritanshu69/Amazon_homepage-#81]
links in the header section are not working.
so i will be adding links to the panel option and panel deals.
I will also be adding more boxes in the shopping sectoin
-->![Screenshot 2024-01-05 154801](https://github.com/Pritanshu69/Amazon_homepage-/assets/125523667/824116c9-6b28-4317-ba23-afa2803c9c47)

**Comment by AnuragMalasi** [comment]
please assign this issue to me under apertre
thanks:)

**Comment by AnuragMalasi** [comment]
@Debaditya-Som please assign this issue to me
thanks:)

**Comment by Debaditya-Som** [comment]
Here you go @AnuragMalasi

**Comment by Debaditya-Som** [comment]
#94
