### ISSUE TITLE
Adding a image slider

### ISSUE THREAD

**Issue by lord-cyclone100** [Pritanshu69/Amazon_homepage-#85]
@Pritanshu69 
I want to add an image slider in place of the top mobile ad banner. 4 images would be there. they would change every 3 seconds. Also there would be forward and backward arrows which would enable users to change the pics manually by adding some javascript

**Comment by Pritanshu69** [comment]
Here you go @lord-cyclone100 brother!

**Comment by harith-hacky03** [comment]
I am eager to work on it . Can you please assign me?

**Comment by Pritanshu69** [comment]
![image](https://github.com/Pritanshu69/Amazon_homepage-/assets/116452282/d695b075-427b-4b71-a754-94dabb5c675c)
