### ISSUE TITLE
Footer can be better in mobile device 

### ISSUE THREAD

**Issue by rko0211** [Pritanshu69/Amazon_homepage-#89]
![f](https://github.com/Pritanshu69/Amazon_homepage-/assets/97402824/ea4f4320-3ec5-478f-bb96-79df24a6f9ce)

**Comment by Pritanshu69** [comment]
ok fine @rko0211 I am assigning this to you here you go!

**Comment by Debaditya-Som** [comment]
hi @rko0211 how are you progressing with this issue?

**Comment by rko0211** [comment]
Yqs i am working on it today o will send PR
