### ISSUE TITLE
To add a discount section

### ISSUE THREAD

**Issue by anjana-18Singh** [Pritanshu69/Amazon_homepage-#93]
To  add a discount section.I wanted to contribute in this project by adding a discount section.  In this section all the dicount product will be visible so that it can be easy for the customer to check their product.customers do  not need to apply filter .so that they can easily access their product

**Comment by Debaditya-Som** [comment]
Here you go @anjana-18Singh

**Comment by Debaditya-Som** [comment]
Hi @anjana-18Singh , how are you progressing with this issue?

**Comment by anjana-18Singh** [comment]
well I completed my issue
