### ISSUE TITLE
Hamburger menu

### ISSUE THREAD

**Issue by lord-cyclone100** [Pritanshu69/Amazon_homepage-#95]
I would like to add this hamburger menu
![Screenshot (328)](https://github.com/Pritanshu69/Amazon_homepage-/assets/121711381/aeebe7c2-a782-47a7-8af7-668c45bbe7d6)

pls assign me this task @Pritanshu69 @Debaditya-Som

**Comment by Debaditya-Som** [comment]
Here you  go @lord-cyclone100

**Comment by Pritanshu69** [comment]
![image](https://github.com/Pritanshu69/Amazon_homepage-/assets/116452282/e3ebd6f1-babd-4f79-8fdf-9d9c943c86be)
