### ISSUE TITLE
The boxes look unarranged

### ISSUE THREAD

**Issue by Debaditya-Som** [Pritanshu69/Amazon_homepage-#96]
![image](https://github.com/Pritanshu69/Amazon_homepage-/assets/121785700/321a7078-9e9c-421b-8181-6e6cbbdb7354)

**Comment by Sneha123-zudo** [comment]
Please assign me this issue , I'm intrested in fixing this issue

**Comment by Debaditya-Som** [comment]
> Please assign me this issue , I'm intrested in fixing this issue

Here you go @Sneha123-zudo

**Comment by Debaditya-Som** [comment]
@Sneha123-zudo how are you progressing with this issue?

**Comment by Sneha123-zudo** [comment]
I'm working on it , i will make PR today.
