### ISSUE TITLE
Adding links to scrolling images

### ISSUE THREAD

**Issue by AnuragMalasi** [Pritanshu69/Amazon_homepage-#97]
These moving images doesn't contain links.
![Screenshot (19)](https://github.com/Pritanshu69/Amazon_homepage-/assets/125523667/6c587c92-8f45-4c45-b51c-9c3110996af9)

**Comment by AnuragMalasi** [comment]
@Debaditya-Som could you please assign this issue to me under apertre
thanks :)

**Comment by Debaditya-Som** [comment]
> @Debaditya-Som could you please assign this issue to me under apertre thanks :)

yep sure go ahead!
